/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package APPS;

import Music.MusicPlay;

/**
 *
 * @author Ângela Sebastião e Daniel Domingues com base do Professor António Manso
 */
public class END extends javax.swing.JDialog {

    /**
     * Creates new form END
     */
    public END() {
        initComponents();
        // iniciar mísica
        MusicPlay.getInstance().playMusica("endfinal.wav", 104);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                System.exit(0);
            }
        });
        setSize(800, 560);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SAIR = new javax.swing.JButton();
        MENU = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Wide Latin", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 51));
        jLabel2.setText("O FIM!");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 120, 230, 60);

        jLabel3.setFont(new java.awt.Font("Wide Latin", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 51));
        jLabel3.setText("From You, 2000 Years Ago");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(300, 150, 240, 60);

        SAIR.setBackground(new java.awt.Color(102, 51, 0));
        SAIR.setFont(new java.awt.Font("Felix Titling", 0, 24)); // NOI18N
        SAIR.setForeground(new java.awt.Color(255, 255, 255));
        SAIR.setText("EXIT");
        SAIR.setBorderPainted(false);
        SAIR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SAIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAIRActionPerformed(evt);
            }
        });
        getContentPane().add(SAIR);
        SAIR.setBounds(570, 460, 210, 60);

        MENU.setBackground(new java.awt.Color(102, 51, 0));
        MENU.setFont(new java.awt.Font("Felix Titling", 0, 24)); // NOI18N
        MENU.setForeground(new java.awt.Color(255, 255, 255));
        MENU.setText("RETURN MENU");
        MENU.setBorderPainted(false);
        MENU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENUActionPerformed(evt);
            }
        });
        getContentPane().add(MENU);
        MENU.setBounds(20, 460, 210, 60);

        jLabel1.setFont(new java.awt.Font("Wide Latin", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS/end.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 830, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    /**
     *   terminar o programa
     * @param evt 
     */
    private void SAIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAIRActionPerformed
        System.exit(0);

    }//GEN-LAST:event_SAIRActionPerformed

    
    /**
     * dispose e logo apos criar novo menu e abrir
     * @param evt 
     */
    private void MENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENUActionPerformed
        dispose();
        new menu().setVisible(true);
    }//GEN-LAST:event_MENUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(END.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(END.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(END.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(END.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                END dialog = new END();
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MENU;
    private javax.swing.JButton SAIR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
