/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package APPS;

import Music.MusicPlay;
import PARTS.GameMapConst;
import PARTS.Player;



/**
 *
 * @author Ângela Sebastião e Daniel Domingues com base do Professor António Manso
 */
public class menu extends javax.swing.JFrame {

    /**
     * cria um novo menu
     */
    private Player selectedPlayer; // player selecionado nas configuracoes
    private int selectedLevel; // level selecionado nas configuracoes
    private String[] levelList; // variavel necessaria para a combo box com todos os niveis
    
    /**
     * construtor
     */
    public menu() {
        this.startList(); // gera lista para a combobox
        this.selectedLevel = 0; // level inicial
        initComponents();
       
        MusicPlay.getInstance().playMusica("menufinal.wav", 236);
        setSize(800, 800);
        setLocationRelativeTo(null);
    }


    /**
     * funcao para gerar lista da combo box
     */
    public void startList() {
        // inicia novo array de string com o tamanho igual ao numero maximo de levels
        String[] stringArray = new String[GameMapConst.getMaxLevel()];
        // adicionando valores ao array com um loop do tamanho maximo do level
        for (int i = 0; i <= GameMapConst.getMaxLevel() - 1; i++) {
            stringArray[i] = Integer.toString(i); // usando string
        }
        this.levelList = stringArray;
    }

   
    /**
     *  funcao publica usada pelos filhos como o SKIN.java
      * necessaria para poder passar informacao de filho(SKIN.java) para pai(menu.java)
     * @param player 
     */
    public void setJogador(Player player) {
        this.selectedPlayer = player;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JOGO = new javax.swing.JButton();
        skinb = new javax.swing.JButton();
        help = new javax.swing.JButton();
        SAIR = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color1"));
        jLabel1.setFont(new java.awt.Font("Wide Latin", 0, 56)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("SOKOBAN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 410, 550, 190);

        JOGO.setBackground(new java.awt.Color(153, 204, 255));
        JOGO.setFont(new java.awt.Font("Felix Titling", 0, 12)); // NOI18N
        JOGO.setForeground(new java.awt.Color(0, 0, 204));
        JOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS/caixa.png"))); // NOI18N
        JOGO.setText("PLAY");
        JOGO.setBorderPainted(false);
        JOGO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JOGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JOGOActionPerformed(evt);
            }
        });
        getContentPane().add(JOGO);
        JOGO.setBounds(20, 570, 180, 160);

        skinb.setBackground(new java.awt.Color(153, 204, 255));
        skinb.setFont(new java.awt.Font("Felix Titling", 0, 12)); // NOI18N
        skinb.setForeground(new java.awt.Color(0, 0, 255));
        skinb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS/jogador-substituto.png"))); // NOI18N
        skinb.setText("skin");
        skinb.setBorderPainted(false);
        skinb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        skinb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skinbActionPerformed(evt);
            }
        });
        getContentPane().add(skinb);
        skinb.setBounds(210, 570, 190, 160);

        help.setBackground(new java.awt.Color(153, 204, 255));
        help.setFont(new java.awt.Font("Felix Titling", 0, 12)); // NOI18N
        help.setForeground(new java.awt.Color(0, 0, 255));
        help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS/ajudando.png"))); // NOI18N
        help.setText("help");
        help.setBorderPainted(false);
        help.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });
        getContentPane().add(help);
        help.setBounds(410, 570, 180, 160);

        SAIR.setBackground(new java.awt.Color(153, 204, 255));
        SAIR.setFont(new java.awt.Font("Felix Titling", 0, 12)); // NOI18N
        SAIR.setForeground(new java.awt.Color(0, 0, 255));
        SAIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS/sair.png"))); // NOI18N
        SAIR.setText("EXIT");
        SAIR.setBorderPainted(false);
        SAIR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SAIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAIRActionPerformed(evt);
            }
        });
        getContentPane().add(SAIR);
        SAIR.setBounds(600, 570, 170, 160);

        jLabel4.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 255));
        jLabel4.setText("To You,  2,000 Years From Now");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(260, 520, 330, 50);

        jComboBox1.setBackground(new java.awt.Color(102, 153, 255));
        jComboBox1.setForeground(new java.awt.Color(0, 0, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(this.levelList));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(50, 490, 64, 26);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS/coordsBACK.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * funcao para iniciar jogo
     * @param evt 
     */
    private void JOGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JOGOActionPerformed
        MusicPlay.getInstance().playMusica("game1.wav", 311);
        new GAME1(this.selectedLevel, selectedPlayer);
        setLocationRelativeTo(null);
        setVisible(false);

    }//GEN-LAST:event_JOGOActionPerformed

   
    /**
     * usado para abrir o ecrã de configuracao do personagem
     * @param evt 
     */
    private void skinbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skinbActionPerformed
        new APPS.SKIN(this, true).setVisible(true);
    }//GEN-LAST:event_skinbActionPerformed

   
    /**
     * usado para abrir ecrã de ajuda
     * @param evt 
     */
    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
        new APPS.ajuda1(this, true).setVisible(true);
    }//GEN-LAST:event_helpActionPerformed


    /**
     * usado para sair do jogo
     * @param evt 
     */
    private void SAIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAIRActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SAIRActionPerformed


    
    /**
     * usado para mudar o level inicial selecionado
     * @param evt 
     */
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // transformando de string para inteiro
        selectedLevel = Integer.valueOf(jComboBox1.getItemAt(jComboBox1.getSelectedIndex()));
        this.selectedLevel = selectedLevel;
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new menu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JOGO;
    private javax.swing.JButton SAIR;
    private javax.swing.JButton help;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton skinb;
    // End of variables declaration//GEN-END:variables
}
